=head1 NAME

Acme::Text::Glitch -

=head1 SYNOPSIS

  use Acme::Text::Glitch;

=head1 DESCRIPTION

Acme::Text::Glitch is

=head1 AUTHOR

Shinpei Maruyama E<lt>shinpeim@gmail.comE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

