=head1 NAME

Acme̳::͏Teͪxt::͌G̨l̼i̸t͑ch̆ -ͣ ̈́Ǵlit̒ch yo̶ur ́t͓e̾x͇t͂ like ̹t͗hiͨs̐.

=head1 SYNOPSIS

 use Acme::Text::Glitch;
 use Encode;

 my $tg = Acme::Text::Glitch->new;
 my $glitched_string = $tg->glitch('glitch me');
 pritn encode('utf8',$glitched_string);

=head1 DESCRIPTION

Ȁcme̐::͔Të́xtͬ::Gl̏ĩțc̻h ̇creạte g͎l̀itch̊e͍ḍ ̧t̫ext̿ ̀l̨ike͎ thi̕s.

=head1 METHODS

=head2 new

 Acme::Text::Glitch->new(glitch_level => 4);

you can pass glitch_level to constructor. default is 10.

=head2 glitch_level

 $tg->glitch_level(8);
 $tg->glitch_level; # 8

accessor to glitch_level.

=head2 glitch

 my $glitched_string = $tg->glitch($string);

=head2 unglitch

 my $unglitched_string = $tg->unglitch($glitched_string);

=head1 AUTHOR

Shinpei Maruyama E<lt>shinpeim@gmail.comE<gt>

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

